### ISSUE TITLE
old branch deleted

### ISSUE THREAD

**Issue by themightychris** [BlinkID/blinkid-flutter#3]
Hey, congrats on the new release!

It looks like this repo has been totally scrubbed though of the previous branches. Our work in progress project was using it and now all our builds and CI are failing. Could you make the old branch available somewhere we could point our `pubspec.yaml` at until we're able to migrate over to the new branch?

**Comment by dCubelic** [comment]
Hi @themightychris,

we are sorry about breaking your builds. The branch was now pushed again, but please try to migrate to our official Flutter wrappers now on master branch, or save the branch for your personal use because it will be removed in a few days as it was just a partial feature. 

Best regards,
Dominik

**Comment by themightychris** [comment]
thanks, it was the iOS-only version we were looking for, but we've migrated already. Still, might be helpful to keep available under another branch somewhere and reference from the README for anyone else that needs to transition

**Comment by dCubelic** [comment]
Hi,

I'm glad you were able to migrate. I am closing the issue now.
If you need any further help feel free to reopen it.

Best regards,
Dominik
